CREATE SCHEMA IF NOT EXISTS cari;
CREATE SCHEMA IF NOT EXISTS envanter;
CREATE SCHEMA IF NOT EXISTS fatura;
CREATE SCHEMA IF NOT EXISTS finans;
CREATE SCHEMA IF NOT EXISTS ik;
CREATE SCHEMA IF NOT EXISTS muhasebe;
CREATE SCHEMA IF NOT EXISTS sistem;
CREATE SCHEMA IF NOT EXISTS satinalma;
CREATE SCHEMA IF NOT EXISTS siparis;
CREATE SCHEMA IF NOT EXISTS personel;
CREATE SCHEMA IF NOT EXISTS proje;
CREATE SCHEMA IF NOT EXISTS stok;
CREATE SCHEMA IF NOT EXISTS sube;
CREATE SCHEMA IF NOT EXISTS ticaret;

