-- V11: Cari hesap detay alanlari
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS tur VARCHAR(20);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS il VARCHAR(50);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS ilce VARCHAR(50);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS vergi_dairesi VARCHAR(100);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS yetkili_kisi VARCHAR(100);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS yetkili_telefon VARCHAR(20);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS iban VARCHAR(50);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS notlar VARCHAR(1000);
ALTER TABLE cari.cari_hesap ADD COLUMN IF NOT EXISTS aktif BOOLEAN NOT NULL DEFAULT true;
