-- =====================================================================
-- V156: Cariye ait çoklu adres / iletişim kayıtları (Faz 2.5)
--
-- Bir carinin birden fazla teslimat/fatura adresi olabilir. Cari kartındaki tek
-- `adres` alanı korunur; bu tablo ek adresleri taşır.
--
-- Idempotent: IF NOT EXISTS.
-- =====================================================================

CREATE TABLE IF NOT EXISTS cari.cari_adres (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cari_hesap_id     bigint NOT NULL,
    sirket_id         bigint NOT NULL,
    baslik            varchar(100),
    adres             varchar(500),
    il                varchar(50),
    ilce              varchar(50),
    yetkili_kisi      varchar(100),
    telefon           varchar(20),
    varsayilan        boolean NOT NULL DEFAULT false,
    olusturma_tarihi  timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cari_adres_cari ON cari.cari_adres (cari_hesap_id);
