global:
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - ratelimit
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  traefik:
    address: ":8080"
  metrics:
    address: ":8083"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL:-admin@raspel.com}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

metrics:
  prometheus:
    entryPoint: metrics

accessLog: {}
